apiVersion: v1
kind: ConfigMap
metadata:
  name: user
  namespace: roboshop
data:
  MONGO: "true" # keep true in double quotes
  MONGO_URL: "mongodb://mongodb:27017/user"  # protocol//service-name:service-port/schema
  REDIS_HOST: "redis"